### PR TITLE
Implement king

### PR DESCRIPTION
**Pull request by grezisek1**

### CODE REVIEW

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
# Code Review Report

## Task Requirements Coverage

1. **Identify when a regular checker piece reaches the opposite end of the board (the opponent's back row).**
   - The code identifies when a regular checker piece reaches the opposite end of the board by checking if the piece's y-coordinate is equal to the opponent's back row (lines 96-97 in `logic.js`).

2. **Implement logic to promote the piece to a King piece (Damka) when the promotion condition is met.**
   - The code promotes a regular checker piece to a King piece when it reaches the opponent's back row (lines 98-101 in `controller.js`).

3. **Ensure that the promoted King piece has the ability to move diagonally in any direction, as per Checkers rules.**
   - The code ensures that a King piece can move diagonally in any direction (lines 111-243 in `logic.js`).

4. **Display the King piece visually on the board to distinguish it from regular pieces.**
   - The code does not seem to include any changes related to visually distinguishing King pieces from regular pieces on the board. This requirement is not met.

## Bugs and Improvements

- There are no apparent bugs in the code changes.
- The code could be improved by adding comments to explain complex logic, especially in the `updateKingMoves` function in `logic.js`.
- The `console.log` statements used for debugging should be removed from the final version of the code.
- The code could be made more readable by breaking down complex functions into smaller, more manageable functions.
- The code could be made more efficient by avoiding unnecessary computations, such as recalculating the neighborhood of a piece multiple times in `updateKingMoves`.
- The use of magic numbers (like 1 and 2 for player indices, and 8 and 1 for king candidate rows) could be avoided by defining constants with meaningful names.
- The code could be made more maintainable by avoiding the use of global variables, such as `player1Pieces` and `player2Pieces` in `logic.js`.
- The code could be made more robust by adding error handling, especially for edge cases.

## Code Examples

- Adding comments to explain complex logic:

```javascript
// This function updates the possible moves for a King piece.
updateKingMoves(state, x, y, di, enemyPieces) {
    // ...
}
```

- Removing `console.log` statements:

```javascript
// console.log(`player ${2 - game.state.currentPlayerIndex} has new king`);
```

- Breaking down complex functions:

```javascript
updateKingMoves(state, x, y, di, enemyPieces) {
    // ...
    updateKingMovesInDirection(state, x, y, di, enemyPieces, 'fl');
    // ...
}

updateKingMovesInDirection(state, x, y, di, enemyPieces, direction) {
    // ...
}
```

- Avoiding unnecessary computations:

```javascript
updateKingMoves(state, x, y, di, enemyPieces) {
    // ...
    const nbhd = this.updateNBHD(state.data, x, y);
    // ...
}
```

- Avoiding the use of magic numbers:

```javascript
const PLAYER1_INDEX = 1;
const PLAYER2_INDEX = 2;
const PLAYER1_KING_ROW = 8;
const PLAYER2_KING_ROW = 1;
```

- Avoiding the use of global variables:

```javascript
class Logic {
    constructor() {
        this.player1Pieces = [stateValues.piece1, stateValues.king1];
        this.player2Pieces = [stateValues.piece2, stateValues.king2];
    }
    // ...
}
```

- Adding error handling:

```javascript
updateKingMoves(state, x, y, di, enemyPieces) {
    if (x < 0 || x > 9 || y < 0 || y > 9) {
        throw new Error('Invalid piece coordinates');
    }
    // ...
}
```

**Comment by grezisek1** [comment]
> Adding comments to explain complex logic

It's long but not complex. To solve this problem, the `updateKingMovesInDirection` method is implemented. The names of the methods are descriptive enough.

> Avoiding unnecessary computations

It should use O(n) instead of O(4n), but this is not a problem since it is just reading from a static buffer + doing SMI arithmetic.

> Avoiding the use of global variables

No reason to pollute the class scope with these specific LUT's (they are not global by the way).

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
## Code Review Report

### Task Requirements

1. Identify when a regular checker piece reaches the opposite end of the board (the opponent's back row).
2. Implement logic to promote the piece to a King piece (Damka) when the promotion condition is met.
3. Ensure that the promoted King piece has the ability to move diagonally in any direction, as per Checkers rules.
4. Display the King piece visually on the board to distinguish it from regular pieces.

### Code Changes Review

#### js/app.js
The changes in this file are not related to the task requirements. The test function `testGameReset` has been removed and `game.init()` is called.

#### js/modules/controller.js
The changes in this file cover the task requirements partially. The logic to promote a regular checker piece to a King piece when it reaches the opposite end of the board is implemented in the `#movePiece` method. However, there is no code to visually distinguish a King piece from regular pieces on the board.

#### js/modules/logic.js
The changes in this file cover the task requirements partially. The logic to identify when a regular checker piece reaches the opposite end of the board is implemented in the `#updatePlayer` method. The logic to ensure that the promoted King piece can move diagonally in any direction is implemented in the `#updateKingMoves` method. However, there is no code to visually distinguish a King piece from regular pieces on the board.

#### js/modules/state.js
The changes in this file are related to the task requirements. A new property `kingCandidates` is added to `this.analysis` object, which seems to be used for storing the positions of pieces that can be promoted to King pieces.

### Suggestions for Improvement

- In `js/modules/controller.js`, add code in the `#movePiece` method to visually distinguish a King piece from regular pieces on the board when a piece is promoted to a King piece. This can be done by adding a specific class to the piece or changing its color.

- In `js/modules/logic.js`, add code in the `#updateKingMoves` method to visually distinguish a King piece from regular pieces on the board when a piece is promoted to a King piece. This can be done by adding a specific class to the piece or changing its color.

- In `js/modules/state.js`, consider renaming `kingCandidates` to `promotionCandidates` or something similar for better readability and understanding of the code.

- In `js/modules/controller.js`, consider adding comments to the `#movePiece` method explaining the logic for promoting a piece to a King piece.

- In `js/modules/logic.js`, consider adding comments to the `#updatePlayer` and `#updateKingMoves` methods explaining the logic for identifying when a regular checker piece reaches the opposite end of the board and ensuring that the promoted King piece can move diagonally in any direction, respectively.

**Comment by grezisek1** [comment]
> add code in the #movePiece method to visually distinguish a King piece

No need for that. This is already done and working.

> add code in the #updateKingMoves method to visually distinguish a King piece

No need for that. This is already done and working.

> consider renaming kingCandidates to promotionCandidates or something similar

Its not "candidates for a promotion" but "candidates for a king". I will consider removal instead.

> consider adding comments [...] explaining the logic for promoting a piece to a King piece.

Literally three lines of code. No need for that.

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
# Code Review Report

## Task Requirements Coverage

1. **Identify when a regular checker piece reaches the opposite end of the board (the opponent's back row).**
   - The code identifies when a regular checker piece reaches the opposite end of the board by checking the `y` coordinate of the piece in the `#updatePlayer` method in `logic.js`.

2. **Implement logic to promote the piece to a King piece (Damka) when the promotion condition is met.**
   - The code promotes a regular checker piece to a King piece in the `#movePiece` method in `controller.js`.

3. **Ensure that the promoted King piece has the ability to move diagonally in any direction, as per Checkers rules.**
   - The code ensures that the promoted King piece can move diagonally in any direction by implementing the `#updateKingMoves` method in `logic.js`.

4. **Display the King piece visually on the board to distinguish it from regular pieces.**
   - The code does not seem to include any changes related to visual representation of the King piece on the board. This requirement is not met.

## Bugs and Improvements

- In `controller.js`, the `#movePiece` method, there is no check for whether a move is valid or not before making it. This could potentially lead to illegal moves being made.

- In `logic.js`, the `#updateKingMovesInDirection` method, there is no check for whether a move is out of bounds or not. This could potentially lead to moves being made outside of the board.

- In `logic.js`, the `#updateNBHD` method, there is no check for whether a coordinate is out of bounds or not before accessing it. This could potentially lead to accessing data outside of the board.

- In `logic.js`, the `#updatePlayer` method, there is no check for whether a piece is a King or not before updating its moves. This could potentially lead to regular pieces being able to move like Kings.

- In `logic.js`, the `#updateKingMoves` method, there is no check for whether a move results in a capture or not. This could potentially lead to King pieces being able to move over enemy pieces without capturing them.

- In `logic.js`, the `#updateKingMovesInDirection` method, there is no check for whether a move results in a capture or not. This could potentially lead to King pieces being able to move over enemy pieces without capturing them.

- In `logic.js`, the `#updateP1PieceMoves` and `#updateP2PieceMoves` methods, there is no check for whether a move results in a capture or not. This could potentially lead to regular pieces being able to move over enemy pieces without capturing them.

- In `logic.js`, the `#updateP1PieceMoves` and `#updateP2PieceMoves` methods, there is no check for whether a move is out of bounds or not before making it. This could potentially lead to moves being made outside of the board.

## Code Examples

- To check if a move is valid before making it in `controller.js`:

```javascript
if (game.logic.isValidMove(game.state.selected, ci)) {
    this.#movePiece(game, ci);
}
```

- To check if a coordinate is out of bounds before accessing it in `logic.js`:

```javascript
if (x >= 0 && x < 10 && y >= 0 && y < 10) {
    nbhd.fl = boardData[this.xyToDi(x - 1, y - 1)];
} else {
    nbhd.fl = null;
}
```

- To check if a piece is a King before updating its moves in `logic.js`:

```javascript
if (kings.includes(game.state.data[di])) {
    this.#updateKingMoves(game.state, x, y, di, enemyPieces);
} else {
    pieceMovesUpdater.call(this, game.state, x, y, di);
}
```

- To check if a move results in a capture before making it in `logic.js`:

```javascript
if (enemyPieces.includes(nbhd[dirKey])) {
    this.#updateNBHD(state.data, nbhd, nx, ny);
    if (nbhd[dirKey] === stateValues.empty) {
        movesWithTake.push(this.xyToCi(nx, ny));
    }
}
```

- To check if a move is out of bounds before making it in `logic.js`:

```javascript
if (nx >= 0 && nx < 10 && ny >= 0 && ny < 10) {
    movesWithoutTake.push(this.xyToCi(nx, ny));
}
```

**Comment by grezisek1** [comment]
> In controller.js, the #movePiece method, there is no check for whether a move is valid

There is.

> In logic.js, the #updateKingMovesInDirection method, there is no check for whether a move is out of bounds or not

There is.

> In logic.js, the #updateNBHD method, there is no check for whether a coordinate is out of bounds

There is.

> In logic.js, the #updatePlayer method, there is no check for whether a piece is a King or not

There is.

> In logic.js, the #updateKingMoves method, there is no check for whether a move results in a capture or not

Not in spec. Wont do until task.

> In logic.js, the #updateKingMovesInDirection method, there is no check for whether a move results in a capture or not.

Not in spec. Wont do until task.

> In logic.js, the #updateP1PieceMoves and #updateP2PieceMoves methods, there is no check for whether a move results in a capture or not

Not in spec. Wont do until task.

> In logic.js, the #updateP1PieceMoves and #updateP2PieceMoves methods, there is no check for whether a move is out of bounds

There is.

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
## Code Review Report

### Task Requirements Validation

1. Identify when a regular checker piece reaches the opposite end of the board (the opponent's back row).

The code correctly identifies when a regular checker piece reaches the opposite end of the board. This is done in the `#updatePlayer` method in `logic.js` where it checks if the current piece's y-coordinate matches the `kingCandidatesRow` value.

2. Implement logic to promote the piece to a King piece (Damka) when the promotion condition is met.

The code correctly promotes a regular checker piece to a King piece when it reaches the opposite end of the board. This is done in the `#movePiece` method in `controller.js` where it checks if the moved piece is a candidate for promotion and promotes it using the `getPieceAsKing` method from `logic.js`.

3. Ensure that the promoted King piece has the ability to move diagonally in any direction, as per Checkers rules.

The code correctly allows the King piece to move diagonally in any direction. This is done in the `#updateKingMoves` method in `logic.js` where it iterates over all possible directions and checks if the King can move or take an opponent's piece in that direction.

4. Display the King piece visually on the board to distinguish it from regular pieces.

The code does not seem to contain any changes related to visual representation of the King piece. The task requirement is not met.

### Code Quality

The code is generally well-structured and follows good practices. The use of private methods (`#methodName`) helps encapsulate logic and improve readability. However, there are some areas that could be improved:

1. The `#updateKingMovesInDirection` method in `logic.js` has a high cyclomatic complexity due to multiple nested conditions and loops. Consider breaking it down into smaller, more manageable methods.

2. The `#updateP1PieceMoves` and `#updateP2PieceMoves` methods in `logic.js` have a lot of duplicated code. Consider creating a generic method that can handle both cases to reduce code duplication.

3. The `#movePiece` method in `controller.js` could be simplified by moving the promotion logic to a separate method.

4. The `#updateNBHD` method in `logic.js` could be simplified by using a loop to iterate over the directions instead of repeating the same logic for each direction.

### Bugs

No bugs were identified in the provided code changes.

### Suggestions for Improvement

1. In `logic.js`, consider creating a separate method for the promotion logic in `#movePiece` to improve readability and maintainability.

```javascript
#promotePiece(game, ci, di) {
    if (!game.logic.isPieceKing(game.state.data[di])) {
        if (game.logic.getKingCandidates(game).includes(game.state.selected)) {
            game.state.data[di] = game.logic.getPieceAsKing(game.state.data[di]);
        }
    }
}
```

2. In `logic.js`, consider refactoring the `#updateNBHD` method to use a loop to iterate over the directions.

```javascript
#updateNBHD(boardData, nbhd, x, y) {
    const directions = ['fl', 'fr', 'bl', 'br'];
    for (const dir of directions) {
        const [dx, dy] = this.getDirectionOffsets(dir);
        if (this.isInBounds(x + dx, y + dy)) {
            nbhd[dir] = boardData[this.xyToDi(x + dx, y + dy)];
        } else {
            nbhd[dir] = null;
        }
    }
}
```

3. In `logic.js`, consider refactoring the `#updateP1PieceMoves` and `#updateP2PieceMoves` methods to reduce code duplication.

```javascript
#updatePieceMoves(state, x, y, di, enemyPieces) {
    // ...
    if (enemyPieces.includes(nbhd[dir])) {
        this.#updateNBHD(state.data, _nbhd, x + dx, y + dy);
        if (_nbhd[dir] === stateValues.empty) {
            movesWithTake.push(this.xyToCi(x + 2 * dx, y + 2 * dy));
        }
    }
    // ...
}
```

4. In `controller.js`, consider adding logic to visually distinguish King pieces from regular pieces on the board. This could be done by adding a specific class to the King pieces in the `#updateBoard` method.

**Review by Sumick — APPROVED** [review]

**Pull request merged**
